# Training Curriculum 
# this yaml serves as container of the learning curriculum for the agent
# by determining the number of static/dynamic obstacles per stage
# (will carry on training on last stage when threshhold reached)

1:
  static: 0
  dynamic: 0
2:
  static: 0
  dynamic: 4
3:
  static: 0
  dynamic: 8
4:
  static: 0
  dynamic: 12
5:
  static: 0
  dynamic: 14
# 6:
#   static: 0
#   dynamic: 20
# 7:
#   static: 0
#   dynamic: 24
# 8:
#   static: 0
#   dynamic: 28
# 9:
#   static: 0
#   dynamic: 32
